version: '3'
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - postgres-db:/var/lib/postgresql/data

  main-server:
    image: yoad787/social-network-fastapi
    ports:
      - 80:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres


  email-verification-server:
    build:
      context: ./email_verification_server
    ports:
      - 8001:8001
    environment:
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_AUTH_TOKEN_KEY=
      - MAIL_TOKEN_ALGORITHM=
      - MAIL_PORT=
      - MAIL_TOKEN_EXPIRE_HOURS=
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=
      - MONGODB_URL=
      - MONGODB_DB_NAME=
    depends_on:
      - mongodb-email-verification
  
  mongodb-email-verification:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-db:/data/db

  
volumes:
  postgres-db:
  mongo-db: