version: '3'
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data


  main-server:
    build:
      context: ./main_server
    ports:
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/app
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
  

  email-verification-server:
    build:
      context: ./email_verification_server
    ports:
      - 8001:8001
    environment:
      - MAIL_USERNAME=LearningCodeWithMe@gmail.com
      - MAIL_PASSWORD=kimyfyhlpnpnvkgs
      - MAIL_AUTH_TOKEN_KEY=52e96e5ddc97f1ea29b79836c9447b55f529de29d17c106c
      - MAIL_TOKEN_ALGORITHM=HS256
      - MAIL_PORT=587
      - MAIL_TOKEN_EXPIRE_HOURS=1
      - MONGODB_USERNAME=yoad
      - MONGODB_PASSWORD=secret
      - MONGODB_URL=mongodb-email-verification
      - MONGODB_DB_NAME=verification_data
    depends_on:
      - mongodb-email-verification
  
  mongodb-email-verification:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yoad
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-db:/data/db

  
volumes:
  postgres-db:
  mongo-db: