FROM python:3.9

RUN apt-get update \
    && pip install --no-cache-dir --upgrade pip

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8002

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8002"]