"""empty message

Revision ID: 03177734ed42
Revises: 5c655d480e03
Create Date: 2022-01-03 09:31:13.453995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03177734ed42'
down_revision = '5c655d480e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key(None, 'posts', 'groups', ['group_id'], ['groups_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###
