"""new colum verified for user

Revision ID: 043fae44df8a
Revises: 57aa607683cd
Create Date: 2021-11-08 15:11:13.976003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043fae44df8a'
down_revision = '57aa607683cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
