"""

Revision ID: 4a525a3f2c4d
Revises: b3a11ad4f105
Create Date: 2021-11-29 20:44:34.060104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a525a3f2c4d'
down_revision = 'b3a11ad4f105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
