"""worlplace for user

Revision ID: 59e88fcc8a7b
Revises: ced74e5e60c1
Create Date: 2021-11-09 15:18:56.502577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e88fcc8a7b'
down_revision = 'ced74e5e60c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workPlaces',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workPlaces')
    # ### end Alembic commands ###
