"""update join group date new

Revision ID: 5c655d480e03
Revises: b91a9c25fc22
Create Date: 2021-12-09 09:09:47.472686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c655d480e03'
down_revision = 'b91a9c25fc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersInGroups', sa.Column('join_group_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('usersInGroups', 'join_ggroup_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersInGroups', sa.Column('join_ggroup_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('usersInGroups', 'join_group_date')
    # ### end Alembic commands ###
