"""update join group date

Revision ID: b91a9c25fc22
Revises: a8a7424d36a4
Create Date: 2021-12-09 08:57:13.812258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91a9c25fc22'
down_revision = 'a8a7424d36a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
