"""update worlplace

Revision ID: c266dd4f4b7a
Revises: 59e88fcc8a7b
Create Date: 2021-11-09 15:21:47.455119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c266dd4f4b7a'
down_revision = '59e88fcc8a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
