"""new column for UserInGrop

Revision ID: ced6ebfa64fc
Revises: 7fac223561d1
Create Date: 2021-12-05 17:38:19.103384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced6ebfa64fc'
down_revision = '7fac223561d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersInGroups', sa.Column('is_blocked', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('usersInGroups', sa.Column('request_accepted', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersInGroups', 'request_accepted')
    op.drop_column('usersInGroups', 'is_blocked')
    # ### end Alembic commands ###
