"""new colums for user

Revision ID: ced74e5e60c1
Revises: 043fae44df8a
Create Date: 2021-11-09 12:25:48.973416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced74e5e60c1'
down_revision = '043fae44df8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('update_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
