"""update worlplace colums

Revision ID: e3f596978030
Revises: c266dd4f4b7a
Create Date: 2021-11-09 15:23:11.715476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f596978030'
down_revision = 'c266dd4f4b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workPlaces', sa.Column('company_name', sa.String(), server_default='No Company', nullable=False))
    op.add_column('workPlaces', sa.Column('description', sa.String(), server_default='No Description', nullable=False))
    op.add_column('workPlaces', sa.Column('position', sa.String(), server_default='No Position', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workPlaces', 'position')
    op.drop_column('workPlaces', 'description')
    op.drop_column('workPlaces', 'company_name')
    # ### end Alembic commands ###
