site_name: Fastapi Social Network
# site_url: https://test-123/
site_author: Yoad Duani
repo_url: https://github.com/Yoad-Duani/social_network_fastAPI
repo_name: social_network_fastAPI

theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: darkblue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: darkblue
      accent: lime

nav:
  - Overview: ./index.md
  - Deployment Guide: 
    - ./deployment-guide/index.md
    - ./deployment-guide/gcp.md
  - User Guide:
    - ./user-guide/index.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Yoad-Duani
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/yoad-duani

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>