name: ci github page
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
        shell: bash
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: install python version 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
