name: CI Terragrunt Tests - TEST - TEST

on:
  workflow_dispatch:
    inputs:
      github_environment:
        description: "Github environment for envs and secrets"
        type: environment
        default: "testing"
        required: true
      environment:
        description: "Choose an environment to run tests on"
        required: true
        type: choice
        options:
          - _tests
          - prod
          - dev
      skip_contest:
        description: "skip_contest"
        required: true
        type: boolean
        default: true

env:
  #   tf_version: "v1.5.2"
  #   tg_version: "v0.48.0"
  go_version: "1.21.1" # Go (requires version >=1.21.1) for terratest
#   conftest_version: "0.42.0"
#   terratest_dir_unitTests: "./devops_repo/GCP/terratest"
#   # static_test_job_timeout_minutes: 15
#   terratest_unittest_timeout: "60m"

jobs:
  static_test:
    name: "Terragrunt Static Test - Test"
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    env:
      ENV: ${{ secrets.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: terragrunt init test
        uses: ./.github/actions/terragrunt-static-test
        with:
          working_directory: ./devops_repo/GCP/tg-modules/${{ inputs.environment || '_tests' }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: false
          go-version: ${{ env.go_version }}
      - name: terragrunt conftest
        if: ${{ inputs.skip_contest == false }}
        uses: ./.github/actions/terragrunt-conftest
        with:
          working_directory: ./devops_repo/GCP/tg-modules/${{ inputs.environment || '_tests' }}
