apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.1.6
    helm:
      values: |
        auth:
          postgresPassword: 12345678
          username: yoad
          password: 12345678
          database: main
        primary:
          podSecurityContext:
            enabled: false
  destination:
    namespace: postgresql
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
